apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-ssd
  resources:
    requests:
      storage: 20Gi
