import type {
  GateDetailResponse,
  GateListResponse,
  NodeRun,
  OrchestratorAcceptanceScenario,
  ReturnTicket,
  ReviewTask,
  Run,
  Stage2AggregationResponse,
  Stage4StepQueryResponse,
} from "./orchestrator-contract-types"

export const NODE_LABELS: Record<string, string> = {
  N01: "剧本关键要点提炼",
  N02: "美术资产人审 Gate",
  N03: "美术资产质检",
  N08: "Stage1 Gate",
  N11: "关键帧质检",
  N15: "视频质检",
  N18: "Stage2 Shot 审核 Gate",
  N21: "Stage3 Gate",
  N23: "字幕与成片校验",
  N24: "Stage4 串行审核 Gate",
  N26: "版本封板",
}

const baseTimestamps = {
  created_at: "2026-03-07T09:00:00Z",
  updated_at: "2026-03-07T11:45:00Z",
}

function createRun(run: Run): Run {
  return run
}

function createNodeRun(nodeRun: NodeRun): NodeRun {
  return nodeRun
}

function createReviewTask(reviewTask: ReviewTask): ReviewTask {
  return reviewTask
}

function createReturnTicket(returnTicket: ReturnTicket): ReturnTicket {
  return returnTicket
}

const stage2GateRun = createRun({
  id: "run_ep101_v1_main",
  episode_id: "episode_101",
  episode_version_id: "episode_101_v1",
  status: "running",
  current_node_id: "N18",
  plan_json: {
    pipeline: ["N01", "N03", "N08", "N11", "N15", "N18", "N21", "N24", "N26"],
    stage_no: 2,
  },
  is_rerun: false,
  rerun_from_ticket_id: null,
  langgraph_thread_id: "lg-thread-episode-101-v1",
  started_at: "2026-03-07T09:10:00Z",
  finished_at: null,
  created_at: "2026-03-07T09:00:00Z",
  updated_at: "2026-03-07T11:35:00Z",
})

const stage2GateNodeRuns: NodeRun[] = [
  createNodeRun({
    id: "nr_101_01",
    run_id: stage2GateRun.id,
    episode_version_id: stage2GateRun.episode_version_id,
    node_id: "N01",
    agent_role: "orchestrator",
    status: "succeeded",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_101:N01:main",
    input_ref: "minio://runs/episode_101_v1/N01/input.json",
    output_ref: "minio://runs/episode_101_v1/N01/output.json",
    model_provider: "openai",
    model_endpoint: "gpt-4.1",
    comfyui_workflow_id: null,
    api_calls: 1,
    token_in: 1850,
    token_out: 920,
    gpu_seconds: 0,
    cost_cny: 0.54,
    rag_query_count: 1,
    quality_score: 0.93,
    error_code: null,
    error_message: null,
    tags: ["stage_1"],
    started_at: "2026-03-07T09:10:00Z",
    ended_at: "2026-03-07T09:11:10Z",
    duration_s: 70,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_101_03",
    run_id: stage2GateRun.id,
    episode_version_id: stage2GateRun.episode_version_id,
    node_id: "N03",
    agent_role: "execution_agent",
    status: "succeeded",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_101:N03:asset",
    input_ref: "minio://runs/episode_101_v1/N03/input.json",
    output_ref: "minio://runs/episode_101_v1/N03/output.json",
    model_provider: "internal_qc",
    model_endpoint: "qc-score-v1",
    comfyui_workflow_id: null,
    api_calls: 2,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0.18,
    rag_query_count: 0,
    quality_score: 0.91,
    error_code: null,
    error_message: null,
    tags: ["auto_qc"],
    started_at: "2026-03-07T09:11:30Z",
    ended_at: "2026-03-07T09:12:05Z",
    duration_s: 35,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_101_11",
    run_id: stage2GateRun.id,
    episode_version_id: stage2GateRun.episode_version_id,
    node_id: "N11",
    agent_role: "execution_agent",
    status: "succeeded",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_101:N11:keyframe",
    input_ref: "minio://runs/episode_101_v1/N11/input.json",
    output_ref: "minio://runs/episode_101_v1/N11/output.json",
    model_provider: "internal_qc",
    model_endpoint: "continuity-check-v1",
    comfyui_workflow_id: null,
    api_calls: 1,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0.12,
    rag_query_count: 0,
    quality_score: 0.88,
    error_code: null,
    error_message: null,
    tags: ["auto_qc"],
    started_at: "2026-03-07T10:40:00Z",
    ended_at: "2026-03-07T10:40:24Z",
    duration_s: 24,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_101_15",
    run_id: stage2GateRun.id,
    episode_version_id: stage2GateRun.episode_version_id,
    node_id: "N15",
    agent_role: "execution_agent",
    status: "succeeded",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_101:N15:video",
    input_ref: "minio://runs/episode_101_v1/N15/input.json",
    output_ref: "minio://runs/episode_101_v1/N15/output.json",
    model_provider: "internal_qc",
    model_endpoint: "video-qc-v1",
    comfyui_workflow_id: null,
    api_calls: 1,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0.14,
    rag_query_count: 0,
    quality_score: 0.9,
    error_code: null,
    error_message: null,
    tags: ["auto_qc"],
    started_at: "2026-03-07T11:02:00Z",
    ended_at: "2026-03-07T11:02:42Z",
    duration_s: 42,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_101_18",
    run_id: stage2GateRun.id,
    episode_version_id: stage2GateRun.episode_version_id,
    node_id: "N18",
    agent_role: "human_review_entry",
    status: "pending",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_101:N18:shot_gate",
    input_ref: "minio://runs/episode_101_v1/N18/input.json",
    output_ref: null,
    model_provider: null,
    model_endpoint: null,
    comfyui_workflow_id: null,
    api_calls: 0,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0,
    rag_query_count: 0,
    quality_score: null,
    error_code: null,
    error_message: null,
    tags: ["gate_waiting_review"],
    started_at: null,
    ended_at: null,
    duration_s: null,
    created_at: baseTimestamps.created_at,
    updated_at: "2026-03-07T11:35:00Z",
  }),
]

const stage2ReviewTasks: ReviewTask[] = [
  createReviewTask({
    id: "rt_stage2_shot_001",
    episode_id: "episode_101",
    episode_version_id: "episode_101_v1",
    stage_no: 2,
    gate_node_id: "N18",
    review_step_no: 1,
    reviewer_role: "qc_inspector",
    review_granularity: "shot",
    anchor_type: "shot",
    anchor_id: "shot_001",
    status: "approved",
    assignee_id: "qc_zhangsan",
    priority: "normal",
    openclaw_session_id: "oc_session_shot_001",
    payload_json: {
      asset_count: 4,
      preview_url: "https://example.com/mock/shot_001",
    },
    started_at: "2026-03-07T11:00:00Z",
    finished_at: "2026-03-07T11:02:00Z",
    decision: "approve",
    decision_comment: "镜头节奏正常，可放行。",
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createReviewTask({
    id: "rt_stage2_shot_002",
    episode_id: "episode_101",
    episode_version_id: "episode_101_v1",
    stage_no: 2,
    gate_node_id: "N18",
    review_step_no: 1,
    reviewer_role: "qc_inspector",
    review_granularity: "shot",
    anchor_type: "shot",
    anchor_id: "shot_002",
    status: "approved",
    assignee_id: "qc_lisi",
    priority: "normal",
    openclaw_session_id: "oc_session_shot_002",
    payload_json: {
      asset_count: 3,
      preview_url: "https://example.com/mock/shot_002",
    },
    started_at: "2026-03-07T11:04:00Z",
    finished_at: "2026-03-07T11:06:00Z",
    decision: "approve",
    decision_comment: "关键帧连续性通过。",
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createReviewTask({
    id: "rt_stage2_shot_003",
    episode_id: "episode_101",
    episode_version_id: "episode_101_v1",
    stage_no: 2,
    gate_node_id: "N18",
    review_step_no: 1,
    reviewer_role: "qc_inspector",
    review_granularity: "shot",
    anchor_type: "shot",
    anchor_id: "shot_003",
    status: "in_progress",
    assignee_id: "qc_wangwu",
    priority: "high",
    openclaw_session_id: "oc_session_shot_003",
    payload_json: {
      asset_count: 5,
      preview_url: "https://example.com/mock/shot_003",
    },
    started_at: "2026-03-07T11:20:00Z",
    finished_at: null,
    decision: null,
    decision_comment: null,
    created_at: baseTimestamps.created_at,
    updated_at: "2026-03-07T11:35:00Z",
  }),
]

const stage2GateList: GateListResponse = {
  items: [
    {
      review_task_id: "rt_stage2_shot_003",
      episode_id: "episode_101",
      episode_version_id: "episode_101_v1",
      stage_no: 2,
      gate_node_id: "N18",
      review_step_no: 1,
      reviewer_role: "qc_inspector",
      review_granularity: "shot",
      anchor_type: "shot",
      anchor_id: "shot_003",
      status: "in_progress",
      priority: "high",
      openclaw_session_id: "oc_session_shot_003",
      due_at: null,
      payload: {
        asset_count: 5,
        preview_url: "https://example.com/mock/shot_003",
      },
    },
  ],
  total: 1,
}

const stage2GateDetail: GateDetailResponse = {
  review_task_id: "rt_stage2_shot_003",
  episode_id: "episode_101",
  episode_version_id: "episode_101_v1",
  stage_no: 2,
  gate_node_id: "N18",
  review_step_no: 1,
  reviewer_role: "qc_inspector",
  review_granularity: "shot",
  anchor_type: "shot",
  anchor_id: "shot_003",
  status: "in_progress",
  priority: "high",
  openclaw_session_id: "oc_session_shot_003",
  payload: {
    asset_count: 5,
    preview_url: "https://example.com/mock/shot_003",
    score_hint: 0.86,
  },
  review_points: [],
}

const stage2Summary: Stage2AggregationResponse = {
  episode_version_id: "episode_101_v1",
  gate_node_id: "N18",
  approved_count: 2,
  returned_count: 0,
  pending_count: 1,
  total_count: 3,
  all_approved: false,
}

const stage4ReturnedRun = createRun({
  id: "run_ep203_v3_main",
  episode_id: "episode_203",
  episode_version_id: "episode_203_v3",
  status: "failed",
  current_node_id: "N24",
  plan_json: {
    pipeline: ["N18", "N21", "N23", "N24", "N26"],
    stage_no: 4,
  },
  is_rerun: false,
  rerun_from_ticket_id: null,
  langgraph_thread_id: "lg-thread-episode-203-v3",
  started_at: "2026-03-07T08:00:00Z",
  finished_at: "2026-03-07T10:55:00Z",
  created_at: "2026-03-07T07:50:00Z",
  updated_at: "2026-03-07T10:55:00Z",
})

const stage4ReturnedNodeRuns: NodeRun[] = [
  createNodeRun({
    id: "nr_203_18",
    run_id: stage4ReturnedRun.id,
    episode_version_id: stage4ReturnedRun.episode_version_id,
    node_id: "N18",
    agent_role: "human_review_entry",
    status: "succeeded",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_203:N18:shot_gate",
    input_ref: "minio://runs/episode_203_v3/N18/input.json",
    output_ref: "minio://runs/episode_203_v3/N18/output.json",
    model_provider: null,
    model_endpoint: null,
    comfyui_workflow_id: null,
    api_calls: 0,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0,
    rag_query_count: 0,
    quality_score: null,
    error_code: null,
    error_message: null,
    tags: ["gate_released"],
    started_at: "2026-03-07T08:00:00Z",
    ended_at: "2026-03-07T08:10:00Z",
    duration_s: 600,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_203_21",
    run_id: stage4ReturnedRun.id,
    episode_version_id: stage4ReturnedRun.episode_version_id,
    node_id: "N21",
    agent_role: "orchestrator",
    status: "succeeded",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_203:N21:stage3_gate",
    input_ref: "minio://runs/episode_203_v3/N21/input.json",
    output_ref: "minio://runs/episode_203_v3/N21/output.json",
    model_provider: null,
    model_endpoint: null,
    comfyui_workflow_id: null,
    api_calls: 0,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0,
    rag_query_count: 0,
    quality_score: null,
    error_code: null,
    error_message: null,
    tags: ["gate_released"],
    started_at: "2026-03-07T08:12:00Z",
    ended_at: "2026-03-07T08:20:00Z",
    duration_s: 480,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_203_23",
    run_id: stage4ReturnedRun.id,
    episode_version_id: stage4ReturnedRun.episode_version_id,
    node_id: "N23",
    agent_role: "execution_agent",
    status: "succeeded",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_203:N23:subtitle_final_check",
    input_ref: "minio://runs/episode_203_v3/N23/input.json",
    output_ref: "minio://runs/episode_203_v3/N23/output.json",
    model_provider: "internal_qc",
    model_endpoint: "subtitle-check-v1",
    comfyui_workflow_id: null,
    api_calls: 1,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0.21,
    rag_query_count: 0,
    quality_score: 0.95,
    error_code: null,
    error_message: null,
    tags: ["stage_4_input_ready"],
    started_at: "2026-03-07T10:20:00Z",
    ended_at: "2026-03-07T10:22:10Z",
    duration_s: 130,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_203_24",
    run_id: stage4ReturnedRun.id,
    episode_version_id: stage4ReturnedRun.episode_version_id,
    node_id: "N24",
    agent_role: "human_review_entry",
    status: "failed",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_203:N24:stage4_gate",
    input_ref: "minio://runs/episode_203_v3/N24/input.json",
    output_ref: null,
    model_provider: null,
    model_endpoint: null,
    comfyui_workflow_id: null,
    api_calls: 0,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0,
    rag_query_count: 0,
    quality_score: null,
    error_code: "RETURNED_BY_REVIEW",
    error_message: "Stage4 Step2 returned",
    tags: ["gate_stopped"],
    started_at: "2026-03-07T10:30:00Z",
    ended_at: "2026-03-07T10:55:00Z",
    duration_s: 1500,
    created_at: baseTimestamps.created_at,
    updated_at: "2026-03-07T10:55:00Z",
  }),
]

const stage4ReviewTasks: ReviewTask[] = [
  createReviewTask({
    id: "rt_stage4_step_1",
    episode_id: "episode_203",
    episode_version_id: "episode_203_v3",
    stage_no: 4,
    gate_node_id: "N24",
    review_step_no: 1,
    reviewer_role: "qc_inspector",
    review_granularity: "episode",
    anchor_type: null,
    anchor_id: null,
    status: "skipped",
    assignee_id: null,
    priority: "normal",
    openclaw_session_id: null,
    payload_json: {
      final_cut_preview_url: "https://example.com/mock/final-cut-v3",
    },
    started_at: null,
    finished_at: "2026-03-07T10:28:00Z",
    decision: null,
    decision_comment: "optional_step_skipped",
    created_at: baseTimestamps.created_at,
    updated_at: "2026-03-07T10:28:00Z",
  }),
  createReviewTask({
    id: "rt_stage4_step_2",
    episode_id: "episode_203",
    episode_version_id: "episode_203_v3",
    stage_no: 4,
    gate_node_id: "N24",
    review_step_no: 2,
    reviewer_role: "middle_platform",
    review_granularity: "episode",
    anchor_type: null,
    anchor_id: null,
    status: "returned",
    assignee_id: "hub_editor_01",
    priority: "high",
    openclaw_session_id: "oc_session_episode_203_step2",
    payload_json: {
      final_cut_preview_url: "https://example.com/mock/final-cut-v3",
      subtitle_bundle_url: "https://example.com/mock/subtitles-v3",
    },
    started_at: "2026-03-07T10:30:00Z",
    finished_at: "2026-03-07T10:55:00Z",
    decision: "return",
    decision_comment: "字幕在 1200ms 出现错位，需回炉修正。",
    created_at: baseTimestamps.created_at,
    updated_at: "2026-03-07T10:55:00Z",
  }),
]

const stage4GateList: GateListResponse = {
  items: [],
  total: 0,
}

const stage4GateDetail: GateDetailResponse = {
  review_task_id: "rt_stage4_step_2",
  episode_id: "episode_203",
  episode_version_id: "episode_203_v3",
  stage_no: 4,
  gate_node_id: "N24",
  review_step_no: 2,
  reviewer_role: "middle_platform",
  review_granularity: "episode",
  anchor_type: null,
  anchor_id: null,
  status: "returned",
  priority: "high",
  openclaw_session_id: "oc_session_episode_203_step2",
  payload: {
    final_cut_preview_url: "https://example.com/mock/final-cut-v3",
    subtitle_bundle_url: "https://example.com/mock/subtitles-v3",
  },
  review_points: [
    {
      timestamp_ms: 1200,
      issue_type: "subtitle",
      severity: "major",
      comment: "字幕错位，角色对白提前出现。",
    },
  ],
  stage4_progress: {
    current_step_no: 2,
    total_steps: 3,
    previous_steps: [
      {
        step_no: 1,
        status: "skipped",
      },
    ],
  },
}

const stage4Summary: Stage4StepQueryResponse = {
  episode_version_id: "episode_203_v3",
  gate_node_id: "N24",
  current_step_no: 2,
  total_steps: 3,
  steps: [
    {
      step_no: 1,
      reviewer_role: "qc_inspector",
      status: "skipped",
    },
    {
      step_no: 2,
      reviewer_role: "middle_platform",
      status: "returned",
    },
    {
      step_no: 3,
      reviewer_role: "partner",
      status: null,
    },
  ],
}

const stage4ReturnTicket = createReturnTicket({
  id: "ticket_episode_203_v3_01",
  episode_id: "episode_203",
  episode_version_id: "episode_203_v3",
  review_task_id: "rt_stage4_step_2",
  source_type: "human_review",
  source_node_id: null,
  stage_no: 4,
  anchor_type: null,
  anchor_id: null,
  timestamp_ms: 1200,
  issue_type: "subtitle",
  severity: "major",
  comment: "字幕错位，建议回退到字幕与成片校验阶段重新生成。",
  created_by_role: "middle_platform",
  suggested_stage_back: 4,
  system_root_cause_node_id: "N23",
  rerun_plan_json: {
    rerun_nodes: ["N23", "N24", "N26"],
    reuse_nodes: ["N01", "N03", "N08", "N11", "N15", "N18", "N21"],
    reason: "subtitle_alignment_fix",
  },
  status: "open",
  resolved_version_id: null,
  created_at: "2026-03-07T10:55:10Z",
  updated_at: "2026-03-07T11:00:00Z",
})

const rerunSourceRun = createRun({
  id: "run_ep304_v1_main",
  episode_id: "episode_304",
  episode_version_id: "episode_304_v1",
  status: "failed",
  current_node_id: "N24",
  plan_json: {
    pipeline: ["N18", "N21", "N23", "N24", "N26"],
    stage_no: 4,
  },
  is_rerun: false,
  rerun_from_ticket_id: null,
  langgraph_thread_id: "lg-thread-episode-304-v1",
  started_at: "2026-03-07T06:00:00Z",
  finished_at: "2026-03-07T08:42:00Z",
  created_at: "2026-03-07T05:55:00Z",
  updated_at: "2026-03-07T08:42:00Z",
})

const rerunActiveRun = createRun({
  id: "run_ep304_v2_rerun",
  episode_id: "episode_304",
  episode_version_id: "episode_304_v2",
  status: "running",
  current_node_id: "N23",
  plan_json: {
    rerun_nodes: ["N23", "N24", "N26"],
    reuse_nodes: ["N01", "N03", "N08", "N11", "N15", "N18", "N21"],
    stage_no: 4,
  },
  is_rerun: true,
  rerun_from_ticket_id: "ticket_episode_304_v1_01",
  langgraph_thread_id: "lg-thread-episode-304-v2-rerun",
  started_at: "2026-03-07T09:20:00Z",
  finished_at: null,
  created_at: "2026-03-07T09:15:00Z",
  updated_at: "2026-03-07T11:45:00Z",
})

const rerunNodeRuns: NodeRun[] = [
  createNodeRun({
    id: "nr_304_v2_18",
    run_id: rerunActiveRun.id,
    episode_version_id: rerunActiveRun.episode_version_id,
    node_id: "N18",
    agent_role: "human_review_entry",
    status: "skipped",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_304:N18:shot_gate",
    input_ref: "minio://runs/episode_304_v2/N18/input.json",
    output_ref: "minio://runs/episode_304_v1/N18/output.json",
    model_provider: null,
    model_endpoint: null,
    comfyui_workflow_id: null,
    api_calls: 0,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0,
    rag_query_count: 0,
    quality_score: null,
    error_code: null,
    error_message: null,
    tags: ["reused_from_previous_version"],
    started_at: "2026-03-07T09:20:00Z",
    ended_at: "2026-03-07T09:20:03Z",
    duration_s: 3,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_304_v2_21",
    run_id: rerunActiveRun.id,
    episode_version_id: rerunActiveRun.episode_version_id,
    node_id: "N21",
    agent_role: "orchestrator",
    status: "skipped",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_304:N21:stage3_gate",
    input_ref: "minio://runs/episode_304_v2/N21/input.json",
    output_ref: "minio://runs/episode_304_v1/N21/output.json",
    model_provider: null,
    model_endpoint: null,
    comfyui_workflow_id: null,
    api_calls: 0,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0,
    rag_query_count: 0,
    quality_score: null,
    error_code: null,
    error_message: null,
    tags: ["reused_from_previous_version"],
    started_at: "2026-03-07T09:20:03Z",
    ended_at: "2026-03-07T09:20:05Z",
    duration_s: 2,
    created_at: baseTimestamps.created_at,
    updated_at: baseTimestamps.updated_at,
  }),
  createNodeRun({
    id: "nr_304_v2_23",
    run_id: rerunActiveRun.id,
    episode_version_id: rerunActiveRun.episode_version_id,
    node_id: "N23",
    agent_role: "execution_agent",
    status: "running",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_304:N23:subtitle_final_check",
    input_ref: "minio://runs/episode_304_v2/N23/input.json",
    output_ref: null,
    model_provider: "internal_qc",
    model_endpoint: "subtitle-check-v1",
    comfyui_workflow_id: null,
    api_calls: 1,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0.09,
    rag_query_count: 0,
    quality_score: null,
    error_code: null,
    error_message: null,
    tags: ["rerun_active"],
    started_at: "2026-03-07T09:22:00Z",
    ended_at: null,
    duration_s: null,
    created_at: baseTimestamps.created_at,
    updated_at: "2026-03-07T11:45:00Z",
  }),
  createNodeRun({
    id: "nr_304_v2_24",
    run_id: rerunActiveRun.id,
    episode_version_id: rerunActiveRun.episode_version_id,
    node_id: "N24",
    agent_role: "human_review_entry",
    status: "pending",
    attempt_no: 1,
    retry_count: 0,
    auto_reject_count: 0,
    scope_hash: "episode_304:N24:stage4_gate",
    input_ref: "minio://runs/episode_304_v2/N24/input.json",
    output_ref: null,
    model_provider: null,
    model_endpoint: null,
    comfyui_workflow_id: null,
    api_calls: 0,
    token_in: 0,
    token_out: 0,
    gpu_seconds: 0,
    cost_cny: 0,
    rag_query_count: 0,
    quality_score: null,
    error_code: null,
    error_message: null,
    tags: ["waiting_for_rerun_result"],
    started_at: null,
    ended_at: null,
    duration_s: null,
    created_at: baseTimestamps.created_at,
    updated_at: "2026-03-07T11:45:00Z",
  }),
]

const rerunReturnTicket = createReturnTicket({
  id: "ticket_episode_304_v1_01",
  episode_id: "episode_304",
  episode_version_id: "episode_304_v1",
  review_task_id: "rt_episode_304_step2",
  source_type: "human_review",
  source_node_id: null,
  stage_no: 4,
  anchor_type: null,
  anchor_id: null,
  timestamp_ms: 860,
  issue_type: "subtitle",
  severity: "major",
  comment: "已生成 rerun plan，v+1 正在修复字幕时序。",
  created_by_role: "middle_platform",
  suggested_stage_back: 4,
  system_root_cause_node_id: "N23",
  rerun_plan_json: {
    rerun_nodes: ["N23", "N24", "N26"],
    reuse_nodes: ["N01", "N03", "N08", "N11", "N15", "N18", "N21"],
    version_strategy: "create_v_plus_1",
  },
  status: "resolved",
  resolved_version_id: "episode_304_v2",
  created_at: "2026-03-07T08:42:10Z",
  updated_at: "2026-03-07T09:16:00Z",
})

export const orchestratorAcceptanceScenarios: OrchestratorAcceptanceScenario[] = [
  {
    id: "stage2_gate_blocked",
    label: "Stage2 卡 Gate",
    description: "展示 shot 级 review_tasks 聚合后，Run 停在 N18 等待人工审核放行。",
    focus_run_id: stage2GateRun.id,
    runs: [stage2GateRun],
    node_runs: stage2GateNodeRuns,
    review_tasks: stage2ReviewTasks,
    return_tickets: [],
    gate_list: stage2GateList,
    gate_detail: stage2GateDetail,
    stage2_summary: stage2Summary,
    stage4_summary: null,
  },
  {
    id: "stage4_returned_with_plan",
    label: "Stage4 打回待回炉",
    description: "展示 Step2 returned 后生成 ReturnTicket 与 rerun_plan_json，后续步骤停止。",
    focus_run_id: stage4ReturnedRun.id,
    runs: [stage4ReturnedRun],
    node_runs: stage4ReturnedNodeRuns,
    review_tasks: stage4ReviewTasks,
    return_tickets: [stage4ReturnTicket],
    gate_list: stage4GateList,
    gate_detail: stage4GateDetail,
    stage2_summary: null,
    stage4_summary: stage4Summary,
  },
  {
    id: "rerun_v_plus_1_running",
    label: "v+1 重跑中",
    description: "展示 ReturnTicket 已绑定新版本，旧版本产物按 node_runs.skipped 复用，新 Run 正在最小重跑。",
    focus_run_id: rerunActiveRun.id,
    runs: [rerunSourceRun, rerunActiveRun],
    node_runs: rerunNodeRuns,
    review_tasks: [],
    return_tickets: [rerunReturnTicket],
    gate_list: null,
    gate_detail: null,
    stage2_summary: null,
    stage4_summary: null,
  },
]
