export type RoadmapTaskStatus = "not_started" | "in_progress" | "done" | "blocked"

export type RoadmapMilestone = "MVP-0" | "MVP-1"

export interface RoadmapTask {
  id: string
  title: string
  milestone: RoadmapMilestone
  phase: string
  estimateHours: number
  completionPercent: number
  status: RoadmapTaskStatus
  summary: string
}

export const roadmapTasks: RoadmapTask[] = [
  {
    id: "T0.2",
    title: "基础设施补齐",
    milestone: "MVP-0",
    phase: "基础设施",
    estimateHours: 20,
    completionPercent: 35,
    status: "in_progress",
    summary: "Redis broker 已确定，TOS 连通已验证，但 CLB / MinIO / 生命周期与 CORS 仍未落地。",
  },
  {
    id: "T0.4",
    title: "环境配置联调",
    milestone: "MVP-0",
    phase: "基础设施",
    estimateHours: 12,
    completionPercent: 75,
    status: "in_progress",
    summary: "连通性脚本和关键环境变量已沉淀，可作为后续并行开发的底座。",
  },
  {
    id: "TM.1",
    title: "VKE GPU 节点池",
    milestone: "MVP-0",
    phase: "模型部署",
    estimateHours: 24,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "TM.2",
    title: "ComfyUI 集群部署",
    milestone: "MVP-0",
    phase: "模型部署",
    estimateHours: 80,
    completionPercent: 0,
    status: "not_started",
    summary: "涉及镜像、模型、workflow、HPA，是 MVP-0 最大工时块之一。",
  },
  {
    id: "TM.3",
    title: "LLM 推理服务",
    milestone: "MVP-0",
    phase: "模型部署",
    estimateHours: 24,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "TM.4",
    title: "音频模型部署",
    milestone: "MVP-0",
    phase: "模型部署",
    estimateHours: 48,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "TM.5",
    title: "模型端点注册与健康监控",
    milestone: "MVP-0",
    phase: "模型部署",
    estimateHours: 16,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T1",
    title: "LangGraph Orchestrator 骨架",
    milestone: "MVP-0",
    phase: "编排核心",
    estimateHours: 32,
    completionPercent: 94,
    status: "in_progress",
    summary: "已完成 graph 状态机、gate、topology、真实 graph compile 与 runtime hook 收口；最新已把主链启动流程接入 `register_all_handlers()` 自动注册，real handlers 可随编排启动自动生效。",
  },
  {
    id: "T2",
    title: "Node Registry 与 DAG 校验",
    milestone: "MVP-0",
    phase: "编排核心",
    estimateHours: 24,
    completionPercent: 100,
    status: "done",
    summary: "已完成 26 节点 node_registry 幂等种子、graph/topology 约束对齐与 DAG 拓扑校验，编排图构建与运行时接线已形成稳定基线。",
  },
  {
    id: "T3",
    title: "Run / NodeRun 状态机",
    milestone: "MVP-0",
    phase: "编排核心",
    estimateHours: 32,
    completionPercent: 97,
    status: "in_progress",
    summary: "第四轮已补真实 runs/node_runs 开发态样本与最小状态联动；第十轮验证 N18 多 shot 聚合，第十一轮验证 N21 episode 级放行，第十二轮验证 N24 串行 3 步放行，4 Gate 全生产化，持续更新 `current_node_id/current_stage_no`。",
  },
  {
    id: "T4",
    title: "4 Gate 挂起与放行",
    milestone: "MVP-0",
    phase: "编排核心",
    estimateHours: 48,
    completionPercent: 100,
    status: "done",
    summary: "第四轮完成最小真实写回骨架，第十到十二轮依次打通 N18/N21/N24，当前 N08/N18/N21/N24 四个 Gate 已全部生产化并完成真闭环收口。",
  },
  {
    id: "T5",
    title: "Artifact 索引与版本固化",
    milestone: "MVP-0",
    phase: "编排核心",
    estimateHours: 24,
    completionPercent: 66,
    status: "in_progress",
    summary: "第六轮已补 round6 artifact fixture、artifacts 真实落库样本、node_run_id 索引与验收页展示；第十轮实测 Stage2 放行后进入 N19，第十一轮实测 Stage3 放行后进入 N22，视觉定稿与成片节点已承接真实 Gate 下游主链。",
  },
  {
    id: "T6",
    title: "质检自动打回",
    milestone: "MVP-0",
    phase: "编排核心",
    estimateHours: 24,
    completionPercent: 100,
    status: "done",
    summary: "已完成 N03/N11/N15 阈值打回、max_auto_rejects 防死循环与 source_type=auto_qc ReturnTicket 写回，自动打回主链闭环已落地。",
  },
  {
    id: "T7",
    title: "RAG 知识库服务",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 32,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T8.1",
    title: "Worker Agent 脚本阶段",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 40,
    completionPercent: 68,
    status: "in_progress",
    summary: "已具备 N01/N02/N04/N05/N06（script_stage）与 N03（qc）真实处理器；随着主链自动注册接入，脚本阶段已从局部实装推进到默认运行链可加载 real handlers。",
  },
  {
    id: "T8.2",
    title: "Worker Agent 美术阶段",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 48,
    completionPercent: 62,
    status: "in_progress",
    summary: "已具备 N06（script_stage）、N07（comfyui_gen）与 N09（freeze）真实处理器，且主链自动注册已接入；当前主要缺口是端到端稳定性与产物质量验收。",
  },
  {
    id: "T8.3",
    title: "Worker Agent 关键帧阶段",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 48,
    completionPercent: 64,
    status: "in_progress",
    summary: "已具备 N10（comfyui_gen）、N11（qc）、N12（analysis）、N13（freeze）真实处理器，且主链自动注册已接入；当前主要缺口是关键帧阶段端到端质量与回炉稳定性验收。",
  },
  {
    id: "T8.4",
    title: "Worker Agent 视频阶段",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 56,
    completionPercent: 72,
    status: "in_progress",
    summary: "已具备 N14（comfyui_gen）、N15（qc）、N16（analysis）、N17/N19（freeze）真实处理器，并完成 N18 shot 级真 Gate 闭环；当前主要缺口是视频阶段端到端质量与性能验收。",
  },
  {
    id: "T8.5",
    title: "Worker Agent 视听阶段",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 40,
    completionPercent: 58,
    status: "in_progress",
    summary: "已具备 N20（av）与 N22（freeze）真实处理器，且 N21 Gate 真闭环已完成并接入主链自动注册；当前主要缺口是视听阶段端到端质量验收与模型实装深度。",
  },
  {
    id: "T8.6",
    title: "Worker Agent 成片阶段",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 32,
    completionPercent: 56,
    status: "in_progress",
    summary: "已具备 N23（av）与 N25/N26（freeze）真实处理器，且 N24 串行三步真 Gate 闭环已完成并接入主链自动注册；当前主要缺口是成片阶段全链稳定性与交付验收。",
  },
  {
    id: "T9",
    title: "Model Gateway Adapter",
    milestone: "MVP-0",
    phase: "智能体",
    estimateHours: 40,
    completionPercent: 56,
    status: "in_progress",
    summary: "第六轮已补共享合同与 route preview，第七轮进一步打通 node_run -> model_jobs -> callback -> node_run 回写的最小真实链路，并真实生成 model_jobs 样本；后续仍需接多 provider SDK、轮询/回调 worker 和下游产物分发。",
  },
  {
    id: "T10",
    title: "ReturnTicket 与 RCA",
    milestone: "MVP-0",
    phase: "回炉与版本",
    estimateHours: 24,
    completionPercent: 68,
    status: "in_progress",
    summary: "第四轮已把真实 return_ticket 写入、review_points 记录和最小 RCA/root-cause 节点映射串起来；后续仍需更细粒度的多问题聚合和 RCA 规则扩展。",
  },
  {
    id: "T11",
    title: "Minimal Rerun Planner",
    milestone: "MVP-0",
    phase: "回炉与版本",
    estimateHours: 20,
    completionPercent: 74,
    status: "in_progress",
    summary: "第四轮已在真实 return 动作中生成 rerun_plan_json，并落入 return_tickets 可视化承接；后续仍需补更完整的图依赖裁剪、节点复用策略和批量计划。",
  },
  {
    id: "T12",
    title: "回炉与新版本自动创建",
    milestone: "MVP-0",
    phase: "回炉与版本",
    estimateHours: 24,
    completionPercent: 64,
    status: "in_progress",
    summary: "第四轮已在 return 动作后自动创建开发态 v+1 episode_version 并回填 rerun run，验收页可见 resolved_version_id；后续仍需接产物复用、版本切换策略和正式回炉完成态。",
  },
  {
    id: "T13",
    title: "角色出场索引",
    milestone: "MVP-1",
    phase: "索引与知识",
    estimateHours: 16,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T14",
    title: "OpenClaw 集成",
    milestone: "MVP-0",
    phase: "网关与人审",
    estimateHours: 32,
    completionPercent: 18,
    status: "in_progress",
    summary: "已完成前端契约对齐、验收页入口和第二轮任务 Tab 承接，尚未接真实 OpenClaw 服务。",
  },
  {
    id: "T15",
    title: "NodeRun 采集与成本归集",
    milestone: "MVP-1",
    phase: "数据与运营",
    estimateHours: 20,
    completionPercent: 40,
    status: "in_progress",
    summary: "第五轮已形成 north-star 事实层，第七轮又把 model_jobs 与 node_run 回写开始纳入执行事实链，后续可继续接真实 provider 成本与 job 级耗时采集。",
  },
  {
    id: "T16",
    title: "Data Center 指标 API",
    milestone: "MVP-1",
    phase: "数据与运营",
    estimateHours: 24,
    completionPercent: 30,
    status: "in_progress",
    summary: "第五轮已新增统一 north-star-summary 读侧契约与 /api/orchestrator/data-center/summary，开始输出成本、质量、吞吐、反馈摘要；后续仍需扩到完整 Data Center API 族。",
  },
  {
    id: "T17",
    title: "AI 诊断",
    milestone: "MVP-1",
    phase: "数据与运营",
    estimateHours: 16,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T18",
    title: "员工质检绩效页后端",
    milestone: "MVP-1",
    phase: "管理页面",
    estimateHours: 16,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T19",
    title: "全局生产大盘后端",
    milestone: "MVP-1",
    phase: "管理页面",
    estimateHours: 20,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T20",
    title: "节点调试页后端",
    milestone: "MVP-1",
    phase: "管理页面",
    estimateHours: 20,
    completionPercent: 99,
    status: "in_progress",
    summary: "第五到第七轮已让 acceptance/trace 承接 truth source、artifact、auto_qc 和 model_jobs；第十轮回填 Stage2，第十一轮回填 Stage3，第十二轮回填 Stage4，任务目录、验收页和 roadmap 均可展示 N08/N18/N21/N24 四 Gate 真实态。",
  },
  {
    id: "T21",
    title: "Review Gateway",
    milestone: "MVP-0",
    phase: "网关与人审",
    estimateHours: 32,
    completionPercent: 96,
    status: "in_progress",
    summary: "第五轮已让 Review Gateway 与 acceptance / Node Trace 共用 truth source 摘要；第十轮让 N18 进入真实多 shot 审核，第十一轮让 N21 进入 episode 级审核，第十二轮让 N24 进入串行 3 步审核，Review API 已能驱动 N08/N18/N21/N24 四 Gate 真闭环。",
  },
  {
    id: "T22",
    title: "安全、审计与幂等",
    milestone: "MVP-1",
    phase: "稳定性",
    estimateHours: 16,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T23",
    title: "可观测与告警",
    milestone: "MVP-1",
    phase: "稳定性",
    estimateHours: 20,
    completionPercent: 0,
    status: "not_started",
    summary: "尚未开始。",
  },
  {
    id: "T24",
    title: "Reflection / Feedback Learning",
    milestone: "MVP-1",
    phase: "智能体进化",
    estimateHours: 36,
    completionPercent: 0,
    status: "not_started",
    summary: "已在 spec 与全局规则中冻结为必须主线，但实现尚未开始。",
  },
  {
    id: "T25",
    title: "质量评测体系",
    milestone: "MVP-1",
    phase: "质量与交付",
    estimateHours: 28,
    completionPercent: 24,
    status: "in_progress",
    summary: "第五轮已把 avg_quality_score、coverage、low_quality、unstable 等指标收口到统一质量摘要，并被 acceptance / Node Trace 消费；后续仍需把这些指标接回自动打回、模型路由与质量 API。",
  },
  {
    id: "T26",
    title: "双制式交付",
    milestone: "MVP-1",
    phase: "质量与交付",
    estimateHours: 24,
    completionPercent: 0,
    status: "not_started",
    summary: "横屏/竖屏双制式已进入 core spec 约束，但尚未进入产线实现。",
  },
  {
    id: "T27",
    title: "审核团队运营",
    milestone: "MVP-1",
    phase: "数据与运营",
    estimateHours: 24,
    completionPercent: 0,
    status: "not_started",
    summary: "审核团队任务池、SLA、负载均衡与运营指标已进入 spec，尚未开始实现。",
  },
  {
    id: "T28",
    title: "真相源统一与 Review Gateway 收口",
    milestone: "MVP-0",
    phase: "治理与收口",
    estimateHours: 20,
    completionPercent: 58,
    status: "in_progress",
    summary: "第五轮已把 truth source 状态正式收口到统一读侧，acceptance / node-trace / data-center 都能看到 preferred_review_task_source=public.review_tasks；后续仍需继续缩减 compat fallback 覆盖面。",
  },
  {
    id: "T29",
    title: "成本与吞吐控制",
    milestone: "MVP-1",
    phase: "成本与扩展",
    estimateHours: 32,
    completionPercent: 0,
    status: "not_started",
    summary: "单分钟 30 元红线与 300->2000+ 分钟产能目标已写入 spec，预算器、路由与并发控制尚未开始。",
  },
]

export function getEquivalentCompletedHours(task: RoadmapTask) {
  return (task.estimateHours * task.completionPercent) / 100
}
